#!/usr/bin/env bash
# same as task 0 but -f added to ln to remove the file if exists
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
rm /run/nginx.pid
